### ISSUE TITLE
Collectives App 2.7.0 gives errors while running background job ExpirePageVersions

### ISSUE THREAD

**Issue by brievenbusalex** [nextcloud/collectives#832] opened 2023-08-13 10:37 UTC
**Describe the bug**
Collectives App gives errors while running background job ExpirePageVersions. 

Argument #3 ($dispatcher) must be of type Symfony\\Component\\EventDispatcher\\EventDispatcherInterface, OC\\EventDispatcher\\EventDispatcher given.

<details>
**Collectives app version:**
2.7.0

**Operating system:**
Almalinx 8

**Web server:**
Apache/2.4.37

**Database:**
MariaDB 10.5.16

**PHP version:**
PHP 8.1.21

**Nextcloud version:** (see Nextcloud admin page)
27.0.2
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"zp48iVriSwSANCftnhuw","level":3,"time":"2023-08-13T06:11:04+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Collectives\\BackgroundJob\\ExpirePageVersions, arguments: )","userAgent":"--","version":"27.0.2.1","exception":{"Exception":"TypeError","Message":"OC\\User\\User::__construct(): Argument #3 ($dispatcher) must be of type Symfony\\Component\\EventDispatcher\\EventDispatcherInterface, OC\\EventDispatcher\\EventDispatcher given, called in /var/www/html/nextcloud/apps/collectives/lib/Versions/CollectiveVersionsExpireManager.php on line 121","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/collectives/lib/Versions/CollectiveVersionsExpireManager.php","line":121,"function":"__construct","class":"OC\\User\\User","type":"->"},{"file":"/var/www/html/nextcloud/apps/collectives/lib/Versions/CollectiveVersionsExpireManager.php","line":96,"function":"expireFolder","class":"OCA\\Collectives\\Versions\\CollectiveVersionsExpireManager","type":"->"},{"file":"/var/www/html/nextcloud/apps/collectives/lib/BackgroundJob/ExpirePageVersions.php","line":35,"function":"expireAll","class":"OCA\\Collectives\\Versions\\CollectiveVersionsExpireManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\Collectives\\BackgroundJob\\ExpirePageVersions","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/html/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/html/nextcloud/lib/private/User/User.php","Line":105,"message":"Error while running background job (class: OCA\\Collectives\\BackgroundJob\\ExpirePageVersions, arguments: )","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Collectives\\BackgroundJob\\ExpirePageVersions, arguments: )"}}
```

</details>

**Comment by juliushaertl** [comment] 2023-08-14 06:24
Closing as duplicate of https://github.com/nextcloud/collectives/issues/828

**Closed by juliushaertl** 2023-08-14 06:24 UTC
Labels: bug
