### ISSUE TITLE
data location is different for different collectives

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/collectives#1208] opened 2024-04-19 12:08 UTC
**Describe the bug**
data location is different for different collectives

have got two collectives: 

- one is - on my view - properly saved/visisble in the nextcloud data folder structure and the appdata folder: ../appdata_xxxxx/collectives/<nr>

  (md files are visible from app "files" and from windows explorer (nc data are in sync)

- the other collectives is - on my view - not properly saved, this structure is only visible in the appdata folder: ../appdata_xxxxx/collectives/<nr>, but not in the the nextcloud data folder structure !

(which is also an issue, regarding the backup mechanism)

**To Reproduce**

All new information in the other collective will NOT being saved in the nextcloud data folder structure.
They are only visible in the ../appdata folder structure !?

**Expected behavior**
ALL productive DATA should be saved into the nextcloud data folder structure.
Caching is OK - but caching (appdata) should not be a permanent way to save data, especially - from my point of view - private user data should NOT be saved into the appdata structure.

The official nextcloud document says:

AppData : (https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/appdata.html#appdata)
Often an app wants to store data. However not all data that is stored belongs with the users files. Often you just want a very simple storage to have some temp files. In order to facilitate this there is the AppData folder that provides each app with a private simple filesystem.

Does this mean, that  - in this case - private user data will be saved in the appData storage, which could be availabe for other users !!???

**Screenshots**

**Server details:**
- Collectives app version: collectives: 2.10.1
- Nextcloud version: 27.1.8
- PHP Version: 8.2
- Database: MariaDB 10.7

**Client details:**
 - OS:Windows
 - Browser: MS Edge Version 123.0.2420.97 (Offizielles Build) (64-Bit)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```


#### Browser log

</details>

**Comment by mejo-** [comment] 2024-05-15 10:23
Dear @Githopp192, thanks for your report. I don't fully understand your situation yet.

The markdown files of all collectives get stored inside the `collectives` folder in your `appdata` folder. That's because a collective is not owned by one particular Nextcloud user. It's owned by a team/circle. Every user that is member of the collective gets the folder from appdata mounted in their home directory (under `Collectives/<name>`).

If you miss a collective folder being mounted into your home folder, that's probably because the user in question is not member of the collective.

Maybe you can explain what problem exactly you face. What's not working as expected?

**Comment by Githopp192** [comment] 2024-05-15 14:40
Dear Jonas, thx a lot for your explantions.

First point: "The markdown files of all collectives get stored inside the collectives folder in your appdata folder."

Yes, according of the nextcloud manual, this makes sense : 

"Appdata is a folder inside of the data directory which contains files that are shared between users and can be put there by the server or apps like avatar images, file previews and cached CSS files for example."

2nd point : "Every user that is member of the collective gets the folder from appdata mounted in their home directory (under Collectives/<name>)."

I found the issue now  .. 

I hadn't thought of that at all (because usually the collective folder in the Sync-Gui (Windows) is checked on the parent folder.
But in this case - Kolletiv_02 (which was not synced from the Windows Sync-Client) - was unchecked.

As soon i did enable the check mark, the folder (as you properly described) did sync also this folder.

For my point of view a miss-behave now was, that i had to confirm each sub-folder with a check sign to make the sync to work (to sync all the collectiv folder data). I had to confirm also every sub-folder in the windows-gui that the sync process did continue to work and i got - surely - 50 of these messages: (the messages confirms, that i had to do those steps for every sub-folder manually, even though the parent folder was marked. May be this is a special - Unfamiliar (and not so comfortable) behave - for all kinds of "external" folders !?

![image](https://github.com/nextcloud/collectives/assets/32612067/85f3a333-4d02-4338-b3bc-6e1df22e6910)

**Comment by Githopp192** [comment] 2024-05-17 20:09
One other thing - dear Jonas - from my previous understanding the appdata has got some of this kind of purpose:

"AppData: Often an app wants to store data. However not all data that is stored belongs with the users files. Often you just want a very simple storage to have some temp files. In order to facilitate this there is the AppData folder that provides each app with a private simple filesystem."

This is from the Developer Manual.
So most of the apps are using the AppData for interim file storage -not for permanent storage for user files.
This can lead to issues regarding Backup & Restore, because - many backup applications do backup the user data folder as per user base.

In your app (collectives), user specific files - as far i see - are located / saved in the appdata-Folder with Folder-Names like ".../11 ", "../12" .. so i suppose you do the user files mapping into the database.

From my point of view this complicates the backup & restore operation - or in other words - when someone (normally the admin) is not aware about this app "behave", there could be some troubles/issues in case of any server crash etc.

In my used case - for example,  my collective folders being mounted into:

-  my home folder in the Web-Gui (my user is a member of the collective in question)
-  my home folder on the Windows PC (synced via sync-Agent)

But my collective folders are NOT visible into the Linux home file pathes in the directory "Kollektives", only in the appdata folder.

**Comment by mejo-** [comment] 2024-05-17 21:57
> From my point of view this complicates the backup & restore operation - or in other words - when someone (normally the admin) is not aware about this app "behave", there could be some troubles/issues in case of any server crash etc.

Well, if the admin doesn't backup the `appdata` directory, they will be in severe trouble anyway. It's not only the Collectives app that stores data permanently there. The groupfolders app does so as well, as do other apps. This is just the logical place to store data if it should not be owned by a particular user account.

From a user perspective you can just backup the folder from your home directory as usual as it's mounted there.

**Closed by mejo-** 2024-05-17 21:57 UTC
Labels: bug, needs info

**Comment by Githopp192** [comment] 2024-05-17 22:01
ok thanks .. and as i mentioned - is this the default behave ? ==>

In my used case - for example, my collective folders being mounted into:

my home folder in the Web-Gui (my user is a member of the collective in question)
my home folder on the Windows PC (synced via sync-Agent)
But my collective folders are NOT visible into the Linux home file pathes in the directory "Kollektives", only in the appdata folder.

**Comment by max-nextcloud** [comment] 2025-12-29 11:55
@PatrickGlatz Sounds like it's behaving as designed. Let me explain.

One of the problems collectives is aiming to solve is collective ownership of the data.

In the default sharing model of nextcloud one person owns the files and it's in their user folder and the other people have access to the share. If the initial user deletes their account or becomes unresponsive the share cannot be changed as there is only one owner. You can transfer the ownership - but that requires the original owner or an admin to perform this.

Collectives on the other hand represent try to establish a shared data ownership. If you create a collective and add someone later they have the same access rights and once you leave they can fully replace you. In order to enable this collectives manages the data in its own folder.

In general you should not rely on the data in your storage folder. Nextcloud does various shenanigans mounting shared files, group folders, the talk folder and so on to build your effective data storage you see in the web ui and via webdav. So if you want to access / backup / sync 'your' files in the nextcloud I'd recommend accessing them via the clients, the web ui or webdav. The server directory is assumed to not be accessible by the individual users.

I hope that explains the situation. If you do not need collective ownership of files you can use the notes app instead. To my knowledge it will store the files in the users folder.
