### ISSUE TITLE
[Bug] Courser cannot be placed in new lines when editing page

### ISSUE THREAD

**Issue by CWempe** [nextcloud/collectives#630] opened 2023-04-01 21:16 UTC
**Describe the bug**
Courser cannot be placed in new lines when editing page.

**To Reproduce**
1. Open Collectives in Android Chrome
2. Add a new page
3. type something
4. hit enter

**Expected behavior**
A new line should be created and the courser should move to that line

**Screenshots**

https://user-images.githubusercontent.com/1270359/229314150-af40e757-3e0a-4f87-847b-ad3769ee8d4e.mp4

**Client details:**
 - OS: Android 13
 - Browser: Chome
 - Version: 26
 - Device: Samsung S22+

<details>
<summary>Server details</summary>

**Collectives app version:** 2.4.0

**Operating system:** Docker (Denbian)

**Web server:** Apache

**Database:** MariaDB

**PHP version:** ?

**Nextcloud version:** 26

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Relevant?
```

#### Browser log
```
How do I get these on Android?
```

</details>

**Comment by mejo-** [comment] 2023-06-06 14:08
Dear @CWempe, thanks for your report. I'm unable to reproduce this issue on latest Nextcloud 26.0.2 and I guess it has been fixed in the meantime. Could you check whether you're still able to reproduce it after upgrading to Nextcloud 26.0.2 and report back here?

**Closed by mejo-** 2023-06-06 14:08 UTC
Labels: bug

**Comment by mejo-** [comment] 2023-06-06 14:10
Oh, only now tested on Chrome and indeed there I'm able to reproduce. Not reproducible on Firefox Mobile though.

**Comment by mejo-** [comment] 2023-06-06 14:12
I'll transfer the issue to Nextcloud Text.
