### ISSUE TITLE
Can't use circles

### ISSUE THREAD

**Issue by l3ochan** [nextcloud/collectives#1184] opened 2024-04-03 21:49 UTC
**Describe the bug**
I can't use the app since the circles app is unstable

**To Reproduce**
1. Install the collective app
2. Try to open the collective app
3. The collective app does not open and users are greeted with a message asking me to enable the circles app but since the app doesn't really get support anymore I can't install it (nextcloud won't let me 
![image](https://github.com/nextcloud/collectives/assets/81470534/06d8e1ff-5336-40de-8cf0-74100f4e9a1b))

**Expected behavior**
The collective app should open

**Screenshots**
![image](https://github.com/nextcloud/collectives/assets/81470534/e27e61b7-2be3-4c36-83e4-26b570a71e0a)

**Server details:**
- Collectives app version: 2.10.1
- Nextcloud version: 28.0.4
- PHP Version: 8.1
- Database: MariaDB 15.1

**Client details:**
 - OS: Windows 11
 - Browser: Brave 
 - Browser version: 1.64.113
 - Device: Desktop 

The circles app is now deprecated, it shouldn't be needed for this app to operate

**Comment by mejo-** [comment] 2024-04-04 06:30
Dear @l3ochan, circles should have come preinstalled with your Nextcloud. Also, it's by no means deprecated - why do you think so?

It seems though that you have a *very* old version of the circles app on your system. 0.21.4 is more then 3 years old. As mentioned, along with Nextcloud 28 you should have circles version 28.0.0 installed.

How did you (try to) install the circles app?

**Comment by mejo-** [comment] 2024-04-04 06:30
I'll close this issue as it's not a bug in collectives.

**Closed by mejo-** 2024-04-04 06:30 UTC
Labels: bug

**Comment by l3ochan** [comment] 2024-04-04 07:33
> How did you (try to) install the circles app?

Hi, thanks for your reply. My nextcloud instance did not come with circles initially. I had to install it through the store. But since then the updates were handled by nc updater. I'm encountering lots of errors (thousands of errors related to some picture asset not present in the root of my nc install) when the circles app is active and users try to go to the activity app. I tried rolling back versions and reinstalling it from the latest nextcloud archive available on the official site (the one for NC 28.0.4) but with no luck. The app is still named circles tho, not teams as I read this was the new name for the app, does this new name only appear in nc 29?
Because its not an issue directly related to Collectives, I don't think there's a point continuing further with this issue, help will be appreciated if you know why I'm getting these errors because I have no idea where this comes from. 
thanks

**Comment by mejo-** [comment] 2024-04-04 07:48
> My nextcloud instance did not come with circles initially. I had to install it through the store.

What version of Nextcloud did you install initially? And which way? Circles comes shipped (and enabled) with the Nextcloud release tarballs since Nextcloud 22. Did you install from the release tarball linked from the website? Or did you by any chance download the release tarball from Github? The latter is not recommended and missing many things.

I now had a look at the app store, and there indeed circles 0.21.4 is the latest version of the app - because starting with Nextcloud 22 the app got shipped with Nextcloud and is no longer published through the app store.

You probably should reinstall using an official tarball linked from the Nextcloud website.

> The app is still named circles tho, not teams as I read this was the new name for the app, does this new name only appear in nc 29?

Exactly. The internal app id will not change, it will stay "circles", but the user-facing app name changes to "teams" starting with Nextcloud 29. For lower Nextcloud versions, it will stay "circles".
