### ISSUE TITLE
saved pictures via (ctrl-v) will not be properly saved from time to time into page context

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/collectives#1151] opened 2024-03-10 13:39 UTC
Describe the bug

saved pictures via (ctrl-v) will not be properly saved from time to time:

![image](https://github.com/nextcloud/collectives/assets/32612067/310a7a91-4642-460c-8d9c-e23dcbed4d37)

When clicking on this image:

![image](https://github.com/nextcloud/collectives/assets/32612067/5a5c716d-8e4b-433c-af4f-821a140411ac)

a complete other picture is shown:

other pictures are not there anymore.
clicking on some of the sub-pages ends-up with showing an empty page.

To Reproduce

Can be reproced regulary by pasting different pictures.

A possible explanation for this issue could be that, be pasting (ctrl-v) an image, the image will be saved as 
"image.pgn" if you will save more than one image into the same page, those images will be saved as "image (2).pgn" .. "image (3).pgn"

it seems, that some of this pictures (like image.pgn) will be overwritten by other pages.

Server details:

Collectives app version: 2.9.2
Nextcloud version: 27.1.7
PHP Version: 8.2
Database: MariaDB
Client details:

OS: RHEL 8.9
Browser: MS Edge
Browser version: Version 122.0.2365.66 (Offizielles Build) (64-Bit)
Device: desktop

**Comment by Aveyron-RetD** [comment] 2024-03-11 07:54
I think this is duplicate of #1112

**Closed** 2024-03-11 10:40 UTC
Labels: bug
