### ISSUE TITLE
Tables not following nextcloud enforced light design when device is in darkmode

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#437] opened 2022-11-29 18:56 UTC
In GitLab by @maxris on Nov 29, 2022, 19:56

### Issue Description
When using a device in darkmode and having the light mode enforced in nextcloud accessibility settings, tables in Collectives are still following the Dark/Light-Mode setting from the device. This does however not apply to the text color, so you can't read the text (black on black)

_Nextcloud Version 25.0.1
Collectives 2.1.1
Chrome Browser 107.0.5304.107_

![issue_screen1](https://gitlab.com/collectivecloud/collectives/uploads/30da74880d943f4aa61814592d36a961/issue_screen1.png)

**Comment by juliushaertl** [comment] 2022-12-21 11:38
Seems to be an upstream issue of text so I'll close this as a duplicate of https://github.com/nextcloud/text/issues/3369

**Closed by juliushaertl** 2022-12-21 11:38 UTC
