### ISSUE TITLE
Public shares are empty

### ISSUE THREAD

**Issue by l3ochan** [nextcloud/collectives#1285] opened 2024-05-22 09:57 UTC
**Describe the bug**

**To Reproduce**
1. Create a collective
2. Create a public share link
3. Open the link in a private tab
4. Page opens but is completely empty 

**Expected behavior**
My full collective should appear with all its pages and content 

**Screenshots**
![image](https://github.com/nextcloud/collectives/assets/81470534/c6c96cdf-9de2-44cb-9c45-f5ae15a2cec8) a new collective opened in my account

![image](https://github.com/nextcloud/collectives/assets/81470534/3b29bfa6-4eb6-4fe4-8c1a-56e39ea72438) The public share link of this collective opened in a private browser tab as you can see its completely empty

**Server details:**
- Collectives app version: 2.11.0
- Nextcloud version: 29.0.0
- PHP Version: [8.2
- Database: MariaDB 10.6.16

**Client details:**
 - OS: Windows 11
 - Browser: Brave 
 - Browser version: Brave 1.66.110 Chromium 125.0.6422.60
 - Device: Desktop

**Comment by mejo-** [comment] 2024-05-22 10:53
@l3ochan since you closed this issue straight away: did you find a solution to your problem? If so, what was it? I'm curious because others face the same problem (tracked in #1027) and so far I didn't manage to reproduce or understand the problem.

**Comment by mejo-** [comment] 2024-05-27 13:29
@l3ochan thanks for the additional input. Let's track this issue in #1027.

**Closed by mejo-** 2024-05-27 13:29 UTC
Labels: bug

**Comment by l3ochan** [comment] 2024-09-12 13:52
I had an app that shows TOS to my users before they can first use their accounts and it shows on public shares too to users that are logged out. And there was an issue with that app because the windows that showed the tos on public shares would not open, and the files would not show until you clicked on the "I read and accept the tos". I disabled the app and its fixed. I think they fixed the app but if you have it install you should check
