### ISSUE TITLE
Rendering issues between Edit and view mode 

### ISSUE THREAD

**Issue by Aveyron-RetD** [nextcloud/collectives#1141] opened 2024-03-07 16:25 UTC
**Describe the bug**
I believe more than one bug report are linked to this one.

**To Reproduce**
1. Use collectives in edit mode
2. Click on view mode
3. See multiple bug reports.

#1096 
#1114 
#1068 

For the moment the only workaround is to not click on view mode and things are displayed "properly"

**Comment by Aveyron-RetD** [comment] 2024-03-08 14:50
Reproducible on 2.10.0

**Comment by juliushaertl** [comment] 2024-03-08 15:02
Thanks for your report, however I don't see how this is different from the already existing ones, so I'll close this as duplicate of the others and we need to track and tackle them individually.

**Closed by juliushaertl** 2024-03-08 15:02 UTC
Labels: bug

**Comment by Aveyron-RetD** [comment] 2024-03-11 07:53
mm, seeing other bugs being added, I think this should be pinned. Only edit mode displays things properly.
#1144 
#1151
