### ISSUE TITLE
Anchor links not working in read-only mode

### ISSUE THREAD

**Issue by m10x** [nextcloud/collectives#1047] opened 2023-12-13 07:26 UTC
**Describe the bug**
All anchors are shown as #undefined when hovering over them in read-only mode. Only when switching to the edit mode the correct anchor is shown, e.g. #h-my-header

https://example.com/apps/collectives/Test/Page?fileId=123456#h-my-header will only open the page without jumping to the anchor. Only when switching to the edit mode and refreshing the page it will jump to the anchor.

When testing this with chromium today, at first it worked as expected. But now it also only shows #undefined as anchor in read-only.

I have this bug since many months.

**Expected behavior**
Hovering / Clicking on an anchor in read-only mode should show the correct anchor and not #undefined. Opening a link with a specified anchor in read-only mode should jump to the anchor.

**Screenshots**

**Server details:**
- Collectives app version: 2.9.2
- Nextcloud version: 28.0.0 (but had the same issue with 27)
- PHP Version: dunno, using nextcloud-db docker
- Database: MySQL, don't know the version, I am using nextcloud-db docker

**Client details:**
 - OS: Ubuntu
 - Browser: Firefox / Chromium
 - Browser version: 120 / 120.0.6099.71
 - Device: Desktop

**Comment by mejo-** [comment] 2024-05-15 12:56
Closing this as a duplicate of #1114 as there's more details there.

**Closed by mejo-** 2024-05-15 12:56 UTC
Labels: bug
